package controller

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/AlanD20/groundplane/internal/common/ids"
	"github.com/AlanD20/groundplane/internal/components"
	"github.com/AlanD20/groundplane/internal/core"
	"github.com/AlanD20/groundplane/internal/infra/etcd"
	"github.com/AlanD20/groundplane/pkg/errs"
	"github.com/AlanD20/groundplane/proto/agentpb"
	composetypes "github.com/compose-spec/compose-go/v2/types"
)

type componentPlanProjectionRenderer struct {
	serviceName string
}

func (renderer componentPlanProjectionRenderer) Render(
	environment core.Environment,
	component core.Component,
) (map[string]components.GeneratedService, map[string][]byte, error) {
	if !component.Enabled {
		return map[string]components.GeneratedService{}, map[string][]byte{}, nil
	}
	services := map[string]components.GeneratedService{
		renderer.serviceName: {
			Service: core.Service{
				ID: component.GeneratedServices[0], Name: renderer.serviceName, Image: "router:1",
				Zones: []string{"frontend"}, Expose: []string{"80"}, Restart: "unless-stopped", Replicas: 1,
			},
			StaticIPv4: map[string]string{"frontend": component.PinnedIPv4},
			Mounts: []components.GeneratedMount{{
				Source: "components/router/config", Target: "/etc/router/config", ReadOnly: true,
			}},
		},
	}
	routeID := "none"
	if len(environment.Routes) != 0 {
		routeID = environment.Routes[0].ID
	}
	files := map[string][]byte{"components/router/config": []byte(routeID + "\n")}
	return services, files, nil
}

func (componentPlanProjectionRenderer) Healthy(core.Environment, core.Component) (bool, error) {
	return true, nil
}

// Rationale: restart-time Component rendering must reuse the exact stable
// Route, Component, and generated Service identities pinned at task creation.
func TestProjectPinnedEnvironmentComponentsRehydratesExactGraph(t *testing.T) {
	project, identity, projection, routeSpecs, catalog := componentPlanProjectionInput(t)

	result, err := projectPinnedEnvironmentComponents(
		project,
		identity,
		projection,
		routeSpecs,
		map[string]core.ComponentSpec{"caddy": {Kind: core.ComponentKindIngressCaddy, Enabled: true}},
		nil,
		catalog,
	)
	if err != nil {
		t.Fatalf("projectPinnedEnvironmentComponents() error = %v", err)
	}
	generated, exists := result.Project.Services["caddy"]
	if !exists || generated.Networks["frontend"].Ipv4Address != "10.70.0.2" ||
		len(result.PlainFiles) != 1 || result.PlainFiles[0].ComponentID != projection.Components[0].Desired.ID ||
		string(result.PlainFiles[0].Content) != projection.Routes[0].ID+"\n" {
		t.Fatalf("Component projection = %#v", result)
	}
}

// Rationale: dispatch must never repair a missing Route identity by allocating
// a new id after the durable Task and its authenticated plan hash exist.
func TestProjectPinnedEnvironmentComponentsRejectsUnpinnedRoute(t *testing.T) {
	project, identity, projection, routeSpecs, catalog := componentPlanProjectionInput(t)
	projection.Routes = nil

	_, err := projectPinnedEnvironmentComponents(
		project,
		identity,
		projection,
		routeSpecs,
		map[string]core.ComponentSpec{"caddy": {Kind: core.ComponentKindIngressCaddy, Enabled: true}},
		nil,
		catalog,
	)
	if !errors.Is(err, errs.New(errs.KindInternal, "")) {
		t.Fatalf("projectPinnedEnvironmentComponents() error = %v, want internal", err)
	}
}

// Rationale: an explicit Route removal candidate must retain enough immutable
// match history to replay the Blueprint while omitting that Route from the
// effective Component renderer input.
func TestProjectPinnedEnvironmentComponentsOmitsSuppressedRoute(t *testing.T) {
	project, identity, projection, routeSpecs, catalog := componentPlanProjectionInput(t)
	next, changed, err := etcd.SuppressEnvironmentRoute(projection, projection.Routes[0].ID)
	if err != nil || !changed {
		t.Fatalf("SuppressEnvironmentRoute() = %#v, %t, %v", next, changed, err)
	}
	result, err := projectPinnedEnvironmentComponents(
		project,
		identity,
		next,
		routeSpecs,
		map[string]core.ComponentSpec{"caddy": {Kind: core.ComponentKindIngressCaddy, Enabled: true}},
		nil,
		catalog,
	)
	if err != nil {
		t.Fatalf("projectPinnedEnvironmentComponents() error = %v", err)
	}
	if len(result.PlainFiles) != 1 || string(result.PlainFiles[0].Content) != "none\n" {
		t.Fatalf("suppressed Component projection = %#v", result)
	}
}

// Rationale: a Controller restart must regenerate the exact Component file
// from retained Blueprint and projection state without stored generated bytes.
func TestTaskPlanResolverRegeneratesPinnedComponentFile(t *testing.T) {
	_, identity, projection, _, catalog := componentPlanProjectionInput(t)
	identity.TenantID = "tnt_01ARZ3NDEKTSV4RRFFQ69G5FAV"
	identity.TenantSlug = "acme"
	identity.ProjectSlug = "shop"
	content := []byte(`kind: environment
schema: 1
metadata: {tenant: acme, project: shop, environment: production}
services:
  api:
    image: api:1
    networks: [frontend]
    expose: ["8080"]
networks:
  frontend:
    ipam:
      config:
        - subnet: 10.70.0.0/24
x-gp-routes:
  - hostname: app.example.com
    path: /app/*
    target: api
    target_port: 8080
    exposure: public
x-gp-components:
  caddy:
    kind: caddy
    enabled: true
`)
	reader := &blueprintPlanReader{
		tenant: etcd.TenantRecord{ID: identity.TenantID, Slug: identity.TenantSlug, Name: "Acme"},
		project: etcd.ProjectRecord{
			ID: identity.ProjectID, TenantID: identity.TenantID, Slug: identity.ProjectSlug,
			Name: "Shop", Kind: etcd.ProjectKindTenant,
		},
		environment: etcd.EnvironmentRecord{
			ID: identity.EnvironmentID, ProjectID: identity.ProjectID, Name: identity.EnvironmentName,
			NetworkPool: "10.70.0.0/16", VolumeDir: identity.AuthorizedVolumeDir,
			ProvisioningState: etcd.EnvironmentProvisioningReady,
		},
		revision: etcd.EnvironmentBlueprintRevision{
			EnvironmentID: identity.EnvironmentID, RevisionID: projection.RevisionID,
			RootPath: "blueprint.yaml", ComposeSources: []string{"blueprint.yaml"},
			Files:     []etcd.EnvironmentBlueprintFile{{Path: "blueprint.yaml", Content: content}},
			CreatedAt: time.Date(2026, 8, 23, 0, 0, 0, 0, time.UTC),
		},
		projection: projection,
	}
	resolver, err := NewTaskPlanResolverWithBlueprints("/var/lib/groundplane/vol", reader)
	if err != nil {
		t.Fatalf("NewTaskPlanResolverWithBlueprints() error = %v", err)
	}
	resolver.componentCatalog = catalog
	actual, err := resolver.ResolveComponentFile(context.Background(), identity.EnvironmentID,
		etcd.TaskComponentFileValueReference{
			RevisionID:  projection.RevisionID,
			ComponentID: projection.Components[0].Desired.ID,
			Path:        "components/router/config",
		})
	if err != nil {
		t.Fatalf("ResolveComponentFile() error = %v", err)
	}
	if string(actual) != projection.Routes[0].ID+"\n" {
		t.Fatalf("ResolveComponentFile() = %q", actual)
	}
}

func componentPlanProjectionInput(
	t *testing.T,
) (*composetypes.Project, pinnedEnvironmentIdentity, etcd.EnvironmentComposeProjection, []core.RouteSpec, []components.Registration) {
	t.Helper()
	at := time.Date(2026, 8, 23, 0, 0, 0, 0, time.UTC)
	environmentID := ids.NewAt(ids.KindEnvironment, at, 1)
	projectID := ids.NewAt(ids.KindProject, at, 2)
	apiID := ids.NewAt(ids.KindService, at, 3)
	caddyServiceID := ids.NewAt(ids.KindService, at, 4)
	caddy, err := etcd.NewComponentRecord(core.Component{
		ID: ids.NewAt(ids.KindComponent, at, 5), Owner: core.ComponentOwnerEnvironment,
		OwnerID: environmentID, Kind: core.ComponentKindIngressCaddy, Enabled: true,
		GeneratedServices: []string{caddyServiceID}, PinnedIPv4: "10.70.0.2",
	})
	if err != nil {
		t.Fatalf("etcd.NewComponentRecord(caddy) error = %v", err)
	}
	tunnel, err := etcd.NewComponentRecord(core.Component{
		ID: ids.NewAt(ids.KindComponent, at, 6), Owner: core.ComponentOwnerEnvironment,
		OwnerID: environmentID, Kind: core.ComponentKindEdgeCloudflare,
	})
	if err != nil {
		t.Fatalf("etcd.NewComponentRecord(tunnel) error = %v", err)
	}
	project := &composetypes.Project{
		Services: composetypes.Services{"api": {
			Name: "api", Image: "api:1", Networks: map[string]*composetypes.ServiceNetworkConfig{"frontend": {}},
			Expose: composetypes.StringOrNumberList{"8080"},
		}},
		Networks: composetypes.Networks{"frontend": {
			Name: "frontend",
			Ipam: composetypes.IPAMConfig{Config: []*composetypes.IPAMPool{{Subnet: "10.70.0.0/24"}}},
		}},
	}
	identity := pinnedEnvironmentIdentity{
		ProjectID: projectID, EnvironmentID: environmentID, EnvironmentName: "production",
		AuthorizedVolumeDir: "/var/lib/groundplane/vol/" + ids.NewAt(ids.KindTenant, at, 7) + "/" +
			projectID + "/" + environmentID,
	}
	projection := etcd.EnvironmentComposeProjection{
		EnvironmentID: environmentID, RevisionID: ids.NewAt(ids.KindTask, at, 8), RenderGeneration: 1,
		Services: []etcd.EnvironmentComposeIdentity{{ID: apiID, Name: "api"}, {ID: caddyServiceID, Name: "caddy"}},
		Networks: []etcd.EnvironmentComposeIdentity{{ID: ids.NewAt(ids.KindNetwork, at, 9), Name: "frontend"}},
		Routes: []etcd.EnvironmentRouteIdentity{{
			ID: ids.NewAt(ids.KindRoute, at, 10), Host: "app.example.com", Path: "/app/*",
		}},
		Components: []etcd.ComponentRecord{caddy, tunnel},
	}
	projection.ComposeArtifact = normalizedProjectionArtifactFixture(
		t,
		ids.NewAt(ids.KindConfig, at, 11),
		environmentID,
		identity.AuthorizedVolumeDir,
		[]byte("services: {}\nnetworks: {}\n"),
		[]*agentpb.ComposeService{
			{ServiceId: apiID, ComposeName: "api"},
			{ServiceId: caddyServiceID, ComposeName: "caddy"},
		},
		nil,
	)
	routeSpecs := []core.RouteSpec{{
		Hostname: "app.example.com", Path: "/app/*", Target: "api", TargetPort: 8080, Exposure: "public",
	}}
	catalog := []components.Registration{
		{
			Kind: core.ComponentKindIngressCaddy, Label: "test caddy",
			AllowedOwners: []core.ComponentOwner{core.ComponentOwnerEnvironment},
			ApplyStrategy: components.EnvironmentRender,
			Environment:   componentPlanProjectionRenderer{serviceName: "caddy"},
		},
		{
			Kind: core.ComponentKindEdgeCloudflare, Label: "test tunnel",
			AllowedOwners: []core.ComponentOwner{core.ComponentOwnerEnvironment},
			ApplyStrategy: components.EnvironmentRender,
			Environment:   componentPlanProjectionRenderer{serviceName: "cloudflare-tunnel"},
		},
	}
	return project, identity, projection, routeSpecs, catalog
}
