// The Controller <-> Agent machine contract. This .proto is the single
// source of truth — both sides compile against it, so a contract change
// is a build error, never a silent runtime mismatch. See mvp.md, "Agent
// channel (locked): gRPC + protobuf".
//
// One long-lived bidirectional stream per agent, INITIATED BY THE AGENT
// (dial-out, pull model): the Agent signals Ready and the Controller
// assigns work; nothing is ever pushed to an unconnected agent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_RUNNING     TaskState = 2
	TaskState_TASK_STATE_COMPLETED   TaskState = 3
	TaskState_TASK_STATE_FAILED      TaskState = 4
	TaskState_TASK_STATE_ABORTED     TaskState = 5
	TaskState_TASK_STATE_TIMED_OUT   TaskState = 6
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_RUNNING",
		3: "TASK_STATE_COMPLETED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_ABORTED",
		6: "TASK_STATE_TIMED_OUT",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_RUNNING":     2,
		"TASK_STATE_COMPLETED":   3,
		"TASK_STATE_FAILED":      4,
		"TASK_STATE_ABORTED":     5,
		"TASK_STATE_TIMED_OUT":   6,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type TaskTerminal int32

const (
	TaskTerminal_TASK_TERMINAL_UNSPECIFIED TaskTerminal = 0
	TaskTerminal_TASK_TERMINAL_COMPLETED   TaskTerminal = 1
	TaskTerminal_TASK_TERMINAL_FAILED      TaskTerminal = 2
	TaskTerminal_TASK_TERMINAL_TIMED_OUT   TaskTerminal = 3
	TaskTerminal_TASK_TERMINAL_ABORTED     TaskTerminal = 4
)

// Enum value maps for TaskTerminal.
var (
	TaskTerminal_name = map[int32]string{
		0: "TASK_TERMINAL_UNSPECIFIED",
		1: "TASK_TERMINAL_COMPLETED",
		2: "TASK_TERMINAL_FAILED",
		3: "TASK_TERMINAL_TIMED_OUT",
		4: "TASK_TERMINAL_ABORTED",
	}
	TaskTerminal_value = map[string]int32{
		"TASK_TERMINAL_UNSPECIFIED": 0,
		"TASK_TERMINAL_COMPLETED":   1,
		"TASK_TERMINAL_FAILED":      2,
		"TASK_TERMINAL_TIMED_OUT":   3,
		"TASK_TERMINAL_ABORTED":     4,
	}
)

func (x TaskTerminal) Enum() *TaskTerminal {
	p := new(TaskTerminal)
	*p = x
	return p
}

func (x TaskTerminal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskTerminal) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[1].Descriptor()
}

func (TaskTerminal) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[1]
}

func (x TaskTerminal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskTerminal.Descriptor instead.
func (TaskTerminal) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

type PlanOperation int32

const (
	PlanOperation_PLAN_OPERATION_UNSPECIFIED     PlanOperation = 0
	PlanOperation_PLAN_OPERATION_RECONCILE       PlanOperation = 1
	PlanOperation_PLAN_OPERATION_DEPLOY          PlanOperation = 2
	PlanOperation_PLAN_OPERATION_ROLLBACK        PlanOperation = 3
	PlanOperation_PLAN_OPERATION_START           PlanOperation = 4
	PlanOperation_PLAN_OPERATION_STOP            PlanOperation = 5
	PlanOperation_PLAN_OPERATION_DESTROY         PlanOperation = 6
	PlanOperation_PLAN_OPERATION_REMOVE          PlanOperation = 7
	PlanOperation_PLAN_OPERATION_COMPONENT_APPLY PlanOperation = 8
)

// Enum value maps for PlanOperation.
var (
	PlanOperation_name = map[int32]string{
		0: "PLAN_OPERATION_UNSPECIFIED",
		1: "PLAN_OPERATION_RECONCILE",
		2: "PLAN_OPERATION_DEPLOY",
		3: "PLAN_OPERATION_ROLLBACK",
		4: "PLAN_OPERATION_START",
		5: "PLAN_OPERATION_STOP",
		6: "PLAN_OPERATION_DESTROY",
		7: "PLAN_OPERATION_REMOVE",
		8: "PLAN_OPERATION_COMPONENT_APPLY",
	}
	PlanOperation_value = map[string]int32{
		"PLAN_OPERATION_UNSPECIFIED":     0,
		"PLAN_OPERATION_RECONCILE":       1,
		"PLAN_OPERATION_DEPLOY":          2,
		"PLAN_OPERATION_ROLLBACK":        3,
		"PLAN_OPERATION_START":           4,
		"PLAN_OPERATION_STOP":            5,
		"PLAN_OPERATION_DESTROY":         6,
		"PLAN_OPERATION_REMOVE":          7,
		"PLAN_OPERATION_COMPONENT_APPLY": 8,
	}
)

func (x PlanOperation) Enum() *PlanOperation {
	p := new(PlanOperation)
	*p = x
	return p
}

func (x PlanOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[2].Descriptor()
}

func (PlanOperation) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[2]
}

func (x PlanOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanOperation.Descriptor instead.
func (PlanOperation) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

type ComposeOwnerKind int32

const (
	ComposeOwnerKind_COMPOSE_OWNER_KIND_UNSPECIFIED ComposeOwnerKind = 0
	ComposeOwnerKind_COMPOSE_OWNER_KIND_ENVIRONMENT ComposeOwnerKind = 1
	ComposeOwnerKind_COMPOSE_OWNER_KIND_PLATFORM    ComposeOwnerKind = 2
)

// Enum value maps for ComposeOwnerKind.
var (
	ComposeOwnerKind_name = map[int32]string{
		0: "COMPOSE_OWNER_KIND_UNSPECIFIED",
		1: "COMPOSE_OWNER_KIND_ENVIRONMENT",
		2: "COMPOSE_OWNER_KIND_PLATFORM",
	}
	ComposeOwnerKind_value = map[string]int32{
		"COMPOSE_OWNER_KIND_UNSPECIFIED": 0,
		"COMPOSE_OWNER_KIND_ENVIRONMENT": 1,
		"COMPOSE_OWNER_KIND_PLATFORM":    2,
	}
)

func (x ComposeOwnerKind) Enum() *ComposeOwnerKind {
	p := new(ComposeOwnerKind)
	*p = x
	return p
}

func (x ComposeOwnerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComposeOwnerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[3].Descriptor()
}

func (ComposeOwnerKind) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[3]
}

func (x ComposeOwnerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComposeOwnerKind.Descriptor instead.
func (ComposeOwnerKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

type Authenticate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // exactly 32 decoded bytes; never the base64url materialization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticate) Reset() {
	*x = Authenticate{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticate) ProtoMessage() {}

func (x *Authenticate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticate.ProtoReflect.Descriptor instead.
func (*Authenticate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Authenticate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Authenticate) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type AgentConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PullIntervalSeconds int32                  `protobuf:"varint,1,opt,name=pull_interval_seconds,json=pullIntervalSeconds,proto3" json:"pull_interval_seconds,omitempty"`
	MaxConcurrentTasks  int32                  `protobuf:"varint,2,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	Labels              map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentConfig) GetPullIntervalSeconds() int32 {
	if x != nil {
		return x.PullIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *AgentConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Authenticate
	//	*AgentMessage_Ready
	//	*AgentMessage_TaskEvent
	//	*AgentMessage_ObservedState
	//	*AgentMessage_TaskAck
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetAuthenticate() *Authenticate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

func (x *AgentMessage) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskEvent() *TaskEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskEvent); ok {
			return x.TaskEvent
		}
	}
	return nil
}

func (x *AgentMessage) GetObservedState() *ObservedState {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ObservedState); ok {
			return x.ObservedState
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskAck() *TaskAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskAck); ok {
			return x.TaskAck
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Authenticate struct {
	Authenticate *Authenticate `protobuf:"bytes,1,opt,name=authenticate,proto3,oneof"` // mandatory first message; no config or work is served before it succeeds
}

type AgentMessage_Ready struct {
	Ready *Ready `protobuf:"bytes,2,opt,name=ready,proto3,oneof"` // idle Ready IS the heartbeat; authoritative for dead-agent detection
}

type AgentMessage_TaskEvent struct {
	TaskEvent *TaskEvent `protobuf:"bytes,3,opt,name=task_event,json=taskEvent,proto3,oneof"` // step progress + streamed output
}

type AgentMessage_ObservedState struct {
	ObservedState *ObservedState `protobuf:"bytes,4,opt,name=observed_state,json=observedState,proto3,oneof"` // drift-detection feed for reconciliation
}

type AgentMessage_TaskAck struct {
	TaskAck *TaskAck `protobuf:"bytes,5,opt,name=task_ack,json=taskAck,proto3,oneof"` // completed / failed
}

func (*AgentMessage_Authenticate) isAgentMessage_Payload() {}

func (*AgentMessage_Ready) isAgentMessage_Payload() {}

func (*AgentMessage_TaskEvent) isAgentMessage_Payload() {}

func (*AgentMessage_ObservedState) isAgentMessage_Payload() {}

func (*AgentMessage_TaskAck) isAgentMessage_Payload() {}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"` // free worker-pool slots
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Ready) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PlanHash      []byte                 `protobuf:"bytes,2,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"` // exactly 32 immutable SHA-256 bytes
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"` // one-based execution attempt for this step
	Ordinal       uint64                 `protobuf:"varint,5,opt,name=ordinal,proto3" json:"ordinal,omitempty"` // one-based stable delivery identity within the step attempt
	State         TaskState              `protobuf:"varint,6,opt,name=state,proto3,enum=groundplane.agent.v1.TaskState" json:"state,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,7,opt,name=chunk,proto3" json:"chunk,omitempty"` // streamed log/output, proxied through the Controller with a short-lived buffer, never persisted in etcd
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetPlanHash() []byte {
	if x != nil {
		return x.PlanHash
	}
	return nil
}

func (x *TaskEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *TaskEvent) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskEvent) GetOrdinal() uint64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *TaskEvent) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskEvent) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ObservedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerState      `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedState) Reset() {
	*x = ObservedState{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedState) ProtoMessage() {}

func (x *ObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedState.ProtoReflect.Descriptor instead.
func (*ObservedState) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ObservedState) GetContainers() []*ContainerState {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // transitional observation payload; typed observation replaces this map before execution is enabled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerState) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerState) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ContainerState) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PlanHash      []byte                 `protobuf:"bytes,2,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"` // exactly 32 immutable SHA-256 bytes
	Terminal      TaskTerminal           `protobuf:"varint,3,opt,name=terminal,proto3,enum=groundplane.agent.v1.TaskTerminal" json:"terminal,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"` // opaque task-type-specific result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAck) GetPlanHash() []byte {
	if x != nil {
		return x.PlanHash
	}
	return nil
}

func (x *TaskAck) GetTerminal() TaskTerminal {
	if x != nil {
		return x.Terminal
	}
	return TaskTerminal_TASK_TERMINAL_UNSPECIFIED
}

func (x *TaskAck) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskAck) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerMessage_TaskAssignment
	//	*ControllerMessage_TaskAbort
	//	*ControllerMessage_ConfigUpdate
	//	*ControllerMessage_Shutdown
	Payload       isControllerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ControllerMessage) GetPayload() isControllerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerMessage) GetTaskAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_TaskAssignment); ok {
			return x.TaskAssignment
		}
	}
	return nil
}

func (x *ControllerMessage) GetTaskAbort() *TaskAbort {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_TaskAbort); ok {
			return x.TaskAbort
		}
	}
	return nil
}

func (x *ControllerMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *ControllerMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isControllerMessage_Payload interface {
	isControllerMessage_Payload()
}

type ControllerMessage_TaskAssignment struct {
	TaskAssignment *TaskAssignment `protobuf:"bytes,1,opt,name=task_assignment,json=taskAssignment,proto3,oneof"` // the full procedure: steps, params, timeout
}

type ControllerMessage_TaskAbort struct {
	TaskAbort *TaskAbort `protobuf:"bytes,2,opt,name=task_abort,json=taskAbort,proto3,oneof"` // cancel in-flight work NOW
}

type ControllerMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,3,opt,name=config_update,json=configUpdate,proto3,oneof"` // applied on next Ready, no restart
}

type ControllerMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,4,opt,name=shutdown,proto3,oneof"`
}

func (*ControllerMessage_TaskAssignment) isControllerMessage_Payload() {}

func (*ControllerMessage_TaskAbort) isControllerMessage_Payload() {}

func (*ControllerMessage_ConfigUpdate) isControllerMessage_Payload() {}

func (*ControllerMessage_Shutdown) isControllerMessage_Payload() {}

type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OperationId    string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // stable across retries
	RetryOf        string                 `protobuf:"bytes,3,opt,name=retry_of,json=retryOf,proto3" json:"retry_of,omitempty"`             // set iff this is a retry of a prior task_id
	Plan           *ExecutionPlan         `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`                                  // complete authoritative procedure
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *TaskAssignment) GetRetryOf() string {
	if x != nil {
		return x.RetryOf
	}
	return ""
}

func (x *TaskAssignment) GetPlan() *ExecutionPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *TaskAssignment) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecutionPlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Schema           uint32                 `protobuf:"varint,1,opt,name=schema,proto3" json:"schema,omitempty"` // exactly 1
	PlanId           string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanHash         []byte                 `protobuf:"bytes,3,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"` // SHA-256 of deterministic serialization with this field cleared
	RenderGeneration uint64                 `protobuf:"varint,4,opt,name=render_generation,json=renderGeneration,proto3" json:"render_generation,omitempty"`
	Operation        PlanOperation          `protobuf:"varint,5,opt,name=operation,proto3,enum=groundplane.agent.v1.PlanOperation" json:"operation,omitempty"`
	TargetId         string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Artifacts        []*ComposeArtifact     `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Steps            []*ExecutionStep       `protobuf:"bytes,8,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionPlan) GetSchema() uint32 {
	if x != nil {
		return x.Schema
	}
	return 0
}

func (x *ExecutionPlan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ExecutionPlan) GetPlanHash() []byte {
	if x != nil {
		return x.PlanHash
	}
	return nil
}

func (x *ExecutionPlan) GetRenderGeneration() uint64 {
	if x != nil {
		return x.RenderGeneration
	}
	return 0
}

func (x *ExecutionPlan) GetOperation() PlanOperation {
	if x != nil {
		return x.Operation
	}
	return PlanOperation_PLAN_OPERATION_UNSPECIFIED
}

func (x *ExecutionPlan) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ExecutionPlan) GetArtifacts() []*ComposeArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ExecutionPlan) GetSteps() []*ExecutionStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ComposeArtifact struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId          string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	OwnerKind           ComposeOwnerKind       `protobuf:"varint,2,opt,name=owner_kind,json=ownerKind,proto3,enum=groundplane.agent.v1.ComposeOwnerKind" json:"owner_kind,omitempty"`
	OwnerId             string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // environment id, or empty for platform
	ProjectName         string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	CanonicalYaml       []byte                 `protobuf:"bytes,5,opt,name=canonical_yaml,json=canonicalYaml,proto3" json:"canonical_yaml,omitempty"`
	YamlSha256          []byte                 `protobuf:"bytes,6,opt,name=yaml_sha256,json=yamlSha256,proto3" json:"yaml_sha256,omitempty"`
	AuthorizedVolumeDir string                 `protobuf:"bytes,7,opt,name=authorized_volume_dir,json=authorizedVolumeDir,proto3" json:"authorized_volume_dir,omitempty"` // empty for platform
	Services            []*ComposeService      `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	Networks            []*ComposeNetwork      `protobuf:"bytes,9,rep,name=networks,proto3" json:"networks,omitempty"`
	Volumes             []*ComposeVolume       `protobuf:"bytes,10,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ComposeArtifact) Reset() {
	*x = ComposeArtifact{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeArtifact) ProtoMessage() {}

func (x *ComposeArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeArtifact.ProtoReflect.Descriptor instead.
func (*ComposeArtifact) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ComposeArtifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ComposeArtifact) GetOwnerKind() ComposeOwnerKind {
	if x != nil {
		return x.OwnerKind
	}
	return ComposeOwnerKind_COMPOSE_OWNER_KIND_UNSPECIFIED
}

func (x *ComposeArtifact) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ComposeArtifact) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ComposeArtifact) GetCanonicalYaml() []byte {
	if x != nil {
		return x.CanonicalYaml
	}
	return nil
}

func (x *ComposeArtifact) GetYamlSha256() []byte {
	if x != nil {
		return x.YamlSha256
	}
	return nil
}

func (x *ComposeArtifact) GetAuthorizedVolumeDir() string {
	if x != nil {
		return x.AuthorizedVolumeDir
	}
	return ""
}

func (x *ComposeArtifact) GetServices() []*ComposeService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ComposeArtifact) GetNetworks() []*ComposeNetwork {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ComposeArtifact) GetVolumes() []*ComposeVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ComposeService struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ComposeName    string                 `protobuf:"bytes,2,opt,name=compose_name,json=composeName,proto3" json:"compose_name,omitempty"`
	ExpectedLabels []*LabelPair           `protobuf:"bytes,3,rep,name=expected_labels,json=expectedLabels,proto3" json:"expected_labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComposeService) Reset() {
	*x = ComposeService{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeService) ProtoMessage() {}

func (x *ComposeService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeService.ProtoReflect.Descriptor instead.
func (*ComposeService) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ComposeService) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ComposeService) GetComposeName() string {
	if x != nil {
		return x.ComposeName
	}
	return ""
}

func (x *ComposeService) GetExpectedLabels() []*LabelPair {
	if x != nil {
		return x.ExpectedLabels
	}
	return nil
}

type ComposeNetwork struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NetworkId      string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ComposeName    string                 `protobuf:"bytes,2,opt,name=compose_name,json=composeName,proto3" json:"compose_name,omitempty"`
	ExpectedLabels []*LabelPair           `protobuf:"bytes,3,rep,name=expected_labels,json=expectedLabels,proto3" json:"expected_labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComposeNetwork) Reset() {
	*x = ComposeNetwork{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeNetwork) ProtoMessage() {}

func (x *ComposeNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeNetwork.ProtoReflect.Descriptor instead.
func (*ComposeNetwork) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ComposeNetwork) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ComposeNetwork) GetComposeName() string {
	if x != nil {
		return x.ComposeName
	}
	return ""
}

func (x *ComposeNetwork) GetExpectedLabels() []*LabelPair {
	if x != nil {
		return x.ExpectedLabels
	}
	return nil
}

type ComposeVolume struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VolumeId       string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	ComposeName    string                 `protobuf:"bytes,2,opt,name=compose_name,json=composeName,proto3" json:"compose_name,omitempty"`
	ExpectedLabels []*LabelPair           `protobuf:"bytes,3,rep,name=expected_labels,json=expectedLabels,proto3" json:"expected_labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComposeVolume) Reset() {
	*x = ComposeVolume{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeVolume) ProtoMessage() {}

func (x *ComposeVolume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeVolume.ProtoReflect.Descriptor instead.
func (*ComposeVolume) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ComposeVolume) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ComposeVolume) GetComposeName() string {
	if x != nil {
		return x.ComposeName
	}
	return ""
}

func (x *ComposeVolume) GetExpectedLabels() []*LabelPair {
	if x != nil {
		return x.ExpectedLabels
	}
	return nil
}

type LabelPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelPair) Reset() {
	*x = LabelPair{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelPair) ProtoMessage() {}

func (x *LabelPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelPair.ProtoReflect.Descriptor instead.
func (*LabelPair) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *LabelPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ExecutionStep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StepId         string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecutionStep_ComposeApply
	//	*ExecutionStep_ComposeStop
	//	*ExecutionStep_ComposeRemove
	//	*ExecutionStep_WaitHealthy
	Payload       isExecutionStep_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStep) Reset() {
	*x = ExecutionStep{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStep) ProtoMessage() {}

func (x *ExecutionStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStep.ProtoReflect.Descriptor instead.
func (*ExecutionStep) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ExecutionStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecutionStep) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecutionStep) GetPayload() isExecutionStep_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionStep) GetComposeApply() *ComposeApply {
	if x != nil {
		if x, ok := x.Payload.(*ExecutionStep_ComposeApply); ok {
			return x.ComposeApply
		}
	}
	return nil
}

func (x *ExecutionStep) GetComposeStop() *ComposeStop {
	if x != nil {
		if x, ok := x.Payload.(*ExecutionStep_ComposeStop); ok {
			return x.ComposeStop
		}
	}
	return nil
}

func (x *ExecutionStep) GetComposeRemove() *ComposeRemove {
	if x != nil {
		if x, ok := x.Payload.(*ExecutionStep_ComposeRemove); ok {
			return x.ComposeRemove
		}
	}
	return nil
}

func (x *ExecutionStep) GetWaitHealthy() *WaitHealthy {
	if x != nil {
		if x, ok := x.Payload.(*ExecutionStep_WaitHealthy); ok {
			return x.WaitHealthy
		}
	}
	return nil
}

type isExecutionStep_Payload interface {
	isExecutionStep_Payload()
}

type ExecutionStep_ComposeApply struct {
	ComposeApply *ComposeApply `protobuf:"bytes,3,opt,name=compose_apply,json=composeApply,proto3,oneof"`
}

type ExecutionStep_ComposeStop struct {
	ComposeStop *ComposeStop `protobuf:"bytes,4,opt,name=compose_stop,json=composeStop,proto3,oneof"`
}

type ExecutionStep_ComposeRemove struct {
	ComposeRemove *ComposeRemove `protobuf:"bytes,5,opt,name=compose_remove,json=composeRemove,proto3,oneof"`
}

type ExecutionStep_WaitHealthy struct {
	WaitHealthy *WaitHealthy `protobuf:"bytes,6,opt,name=wait_healthy,json=waitHealthy,proto3,oneof"`
}

func (*ExecutionStep_ComposeApply) isExecutionStep_Payload() {}

func (*ExecutionStep_ComposeStop) isExecutionStep_Payload() {}

func (*ExecutionStep_ComposeRemove) isExecutionStep_Payload() {}

func (*ExecutionStep_WaitHealthy) isExecutionStep_Payload() {}

type ComposeApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ServiceIds    []string               `protobuf:"bytes,2,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	FullReconcile bool                   `protobuf:"varint,3,opt,name=full_reconcile,json=fullReconcile,proto3" json:"full_reconcile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeApply) Reset() {
	*x = ComposeApply{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeApply) ProtoMessage() {}

func (x *ComposeApply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeApply.ProtoReflect.Descriptor instead.
func (*ComposeApply) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ComposeApply) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ComposeApply) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *ComposeApply) GetFullReconcile() bool {
	if x != nil {
		return x.FullReconcile
	}
	return false
}

type ComposeStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ServiceIds    []string               `protobuf:"bytes,2,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	GraceSeconds  uint32                 `protobuf:"varint,3,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeStop) Reset() {
	*x = ComposeStop{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeStop) ProtoMessage() {}

func (x *ComposeStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeStop.ProtoReflect.Descriptor instead.
func (*ComposeStop) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ComposeStop) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ComposeStop) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *ComposeStop) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type ComposeRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ServiceIds    []string               `protobuf:"bytes,2,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	WholeProject  bool                   `protobuf:"varint,3,opt,name=whole_project,json=wholeProject,proto3" json:"whole_project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeRemove) Reset() {
	*x = ComposeRemove{}
	mi := &file_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeRemove) ProtoMessage() {}

func (x *ComposeRemove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeRemove.ProtoReflect.Descriptor instead.
func (*ComposeRemove) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ComposeRemove) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ComposeRemove) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *ComposeRemove) GetWholeProject() bool {
	if x != nil {
		return x.WholeProject
	}
	return false
}

type WaitHealthy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ServiceIds    []string               `protobuf:"bytes,2,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitHealthy) Reset() {
	*x = WaitHealthy{}
	mi := &file_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitHealthy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitHealthy) ProtoMessage() {}

func (x *WaitHealthy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitHealthy.ProtoReflect.Descriptor instead.
func (*WaitHealthy) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *WaitHealthy) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *WaitHealthy) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

type TaskAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAbort) Reset() {
	*x = TaskAbort{}
	mi := &file_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAbort) ProtoMessage() {}

func (x *TaskAbort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAbort.ProtoReflect.Descriptor instead.
func (*TaskAbort) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *TaskAbort) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAbort) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentConfig   *AgentConfig           `protobuf:"bytes,1,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ConfigUpdate) GetAgentConfig() *AgentConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{23}
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x14groundplane.agent.v1\"?\n" +
	"\fAuthenticate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"\xf5\x01\n" +
	"\vAgentConfig\x122\n" +
	"\x15pull_interval_seconds\x18\x01 \x01(\x05R\x13pullIntervalSeconds\x120\n" +
	"\x14max_concurrent_tasks\x18\x02 \x01(\x05R\x12maxConcurrentTasks\x12E\n" +
	"\x06labels\x18\x03 \x03(\v2-.groundplane.agent.v1.AgentConfig.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x02\n" +
	"\fAgentMessage\x12H\n" +
	"\fauthenticate\x18\x01 \x01(\v2\".groundplane.agent.v1.AuthenticateH\x00R\fauthenticate\x123\n" +
	"\x05ready\x18\x02 \x01(\v2\x1b.groundplane.agent.v1.ReadyH\x00R\x05ready\x12@\n" +
	"\n" +
	"task_event\x18\x03 \x01(\v2\x1f.groundplane.agent.v1.TaskEventH\x00R\ttaskEvent\x12L\n" +
	"\x0eobserved_state\x18\x04 \x01(\v2#.groundplane.agent.v1.ObservedStateH\x00R\robservedState\x12:\n" +
	"\btask_ack\x18\x05 \x01(\v2\x1d.groundplane.agent.v1.TaskAckH\x00R\ataskAckB\t\n" +
	"\apayload\"#\n" +
	"\x05Ready\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\"\xdb\x01\n" +
	"\tTaskEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tplan_hash\x18\x02 \x01(\fR\bplanHash\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12\x18\n" +
	"\aordinal\x18\x05 \x01(\x04R\aordinal\x125\n" +
	"\x05state\x18\x06 \x01(\x0e2\x1f.groundplane.agent.v1.TaskStateR\x05state\x12\x14\n" +
	"\x05chunk\x18\a \x01(\fR\x05chunk\"U\n" +
	"\rObservedState\x12D\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2$.groundplane.agent.v1.ContainerStateR\n" +
	"containers\"\xd9\x01\n" +
	"\x0eContainerState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12H\n" +
	"\x06labels\x18\x04 \x03(\v20.groundplane.agent.v1.ContainerState.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\aTaskAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tplan_hash\x18\x02 \x01(\fR\bplanHash\x12>\n" +
	"\bterminal\x18\x03 \x01(\x0e2\".groundplane.agent.v1.TaskTerminalR\bterminal\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\"\xba\x02\n" +
	"\x11ControllerMessage\x12O\n" +
	"\x0ftask_assignment\x18\x01 \x01(\v2$.groundplane.agent.v1.TaskAssignmentH\x00R\x0etaskAssignment\x12@\n" +
	"\n" +
	"task_abort\x18\x02 \x01(\v2\x1f.groundplane.agent.v1.TaskAbortH\x00R\ttaskAbort\x12I\n" +
	"\rconfig_update\x18\x03 \x01(\v2\".groundplane.agent.v1.ConfigUpdateH\x00R\fconfigUpdate\x12<\n" +
	"\bshutdown\x18\x04 \x01(\v2\x1e.groundplane.agent.v1.ShutdownH\x00R\bshutdownB\t\n" +
	"\apayload\"\xc9\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x19\n" +
	"\bretry_of\x18\x03 \x01(\tR\aretryOf\x127\n" +
	"\x04plan\x18\x04 \x01(\v2#.groundplane.agent.v1.ExecutionPlanR\x04plan\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\xea\x02\n" +
	"\rExecutionPlan\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\rR\x06schema\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1b\n" +
	"\tplan_hash\x18\x03 \x01(\fR\bplanHash\x12+\n" +
	"\x11render_generation\x18\x04 \x01(\x04R\x10renderGeneration\x12A\n" +
	"\toperation\x18\x05 \x01(\x0e2#.groundplane.agent.v1.PlanOperationR\toperation\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12C\n" +
	"\tartifacts\x18\a \x03(\v2%.groundplane.agent.v1.ComposeArtifactR\tartifacts\x129\n" +
	"\x05steps\x18\b \x03(\v2#.groundplane.agent.v1.ExecutionStepR\x05steps\"\xf6\x03\n" +
	"\x0fComposeArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12E\n" +
	"\n" +
	"owner_kind\x18\x02 \x01(\x0e2&.groundplane.agent.v1.ComposeOwnerKindR\townerKind\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12%\n" +
	"\x0ecanonical_yaml\x18\x05 \x01(\fR\rcanonicalYaml\x12\x1f\n" +
	"\vyaml_sha256\x18\x06 \x01(\fR\n" +
	"yamlSha256\x122\n" +
	"\x15authorized_volume_dir\x18\a \x01(\tR\x13authorizedVolumeDir\x12@\n" +
	"\bservices\x18\b \x03(\v2$.groundplane.agent.v1.ComposeServiceR\bservices\x12@\n" +
	"\bnetworks\x18\t \x03(\v2$.groundplane.agent.v1.ComposeNetworkR\bnetworks\x12=\n" +
	"\avolumes\x18\n" +
	" \x03(\v2#.groundplane.agent.v1.ComposeVolumeR\avolumes\"\x9c\x01\n" +
	"\x0eComposeService\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fcompose_name\x18\x02 \x01(\tR\vcomposeName\x12H\n" +
	"\x0fexpected_labels\x18\x03 \x03(\v2\x1f.groundplane.agent.v1.LabelPairR\x0eexpectedLabels\"\x9c\x01\n" +
	"\x0eComposeNetwork\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12!\n" +
	"\fcompose_name\x18\x02 \x01(\tR\vcomposeName\x12H\n" +
	"\x0fexpected_labels\x18\x03 \x03(\v2\x1f.groundplane.agent.v1.LabelPairR\x0eexpectedLabels\"\x99\x01\n" +
	"\rComposeVolume\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12!\n" +
	"\fcompose_name\x18\x02 \x01(\tR\vcomposeName\x12H\n" +
	"\x0fexpected_labels\x18\x03 \x03(\v2\x1f.groundplane.agent.v1.LabelPairR\x0eexpectedLabels\"3\n" +
	"\tLabelPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x85\x03\n" +
	"\rExecutionStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\x12I\n" +
	"\rcompose_apply\x18\x03 \x01(\v2\".groundplane.agent.v1.ComposeApplyH\x00R\fcomposeApply\x12F\n" +
	"\fcompose_stop\x18\x04 \x01(\v2!.groundplane.agent.v1.ComposeStopH\x00R\vcomposeStop\x12L\n" +
	"\x0ecompose_remove\x18\x05 \x01(\v2#.groundplane.agent.v1.ComposeRemoveH\x00R\rcomposeRemove\x12F\n" +
	"\fwait_healthy\x18\x06 \x01(\v2!.groundplane.agent.v1.WaitHealthyH\x00R\vwaitHealthyB\t\n" +
	"\apayload\"w\n" +
	"\fComposeApply\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1f\n" +
	"\vservice_ids\x18\x02 \x03(\tR\n" +
	"serviceIds\x12%\n" +
	"\x0efull_reconcile\x18\x03 \x01(\bR\rfullReconcile\"t\n" +
	"\vComposeStop\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1f\n" +
	"\vservice_ids\x18\x02 \x03(\tR\n" +
	"serviceIds\x12#\n" +
	"\rgrace_seconds\x18\x03 \x01(\rR\fgraceSeconds\"v\n" +
	"\rComposeRemove\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1f\n" +
	"\vservice_ids\x18\x02 \x03(\tR\n" +
	"serviceIds\x12#\n" +
	"\rwhole_project\x18\x03 \x01(\bR\fwholeProject\"O\n" +
	"\vWaitHealthy\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1f\n" +
	"\vservice_ids\x18\x02 \x03(\tR\n" +
	"serviceIds\"<\n" +
	"\tTaskAbort\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"T\n" +
	"\fConfigUpdate\x12D\n" +
	"\fagent_config\x18\x01 \x01(\v2!.groundplane.agent.v1.AgentConfigR\vagentConfig\"\n" +
	"\n" +
	"\bShutdown*\xba\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12TASK_STATE_ABORTED\x10\x05\x12\x18\n" +
	"\x14TASK_STATE_TIMED_OUT\x10\x06*\x9c\x01\n" +
	"\fTaskTerminal\x12\x1d\n" +
	"\x19TASK_TERMINAL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TASK_TERMINAL_COMPLETED\x10\x01\x12\x18\n" +
	"\x14TASK_TERMINAL_FAILED\x10\x02\x12\x1b\n" +
	"\x17TASK_TERMINAL_TIMED_OUT\x10\x03\x12\x19\n" +
	"\x15TASK_TERMINAL_ABORTED\x10\x04*\x93\x02\n" +
	"\rPlanOperation\x12\x1e\n" +
	"\x1aPLAN_OPERATION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PLAN_OPERATION_RECONCILE\x10\x01\x12\x19\n" +
	"\x15PLAN_OPERATION_DEPLOY\x10\x02\x12\x1b\n" +
	"\x17PLAN_OPERATION_ROLLBACK\x10\x03\x12\x18\n" +
	"\x14PLAN_OPERATION_START\x10\x04\x12\x17\n" +
	"\x13PLAN_OPERATION_STOP\x10\x05\x12\x1a\n" +
	"\x16PLAN_OPERATION_DESTROY\x10\x06\x12\x19\n" +
	"\x15PLAN_OPERATION_REMOVE\x10\a\x12\"\n" +
	"\x1ePLAN_OPERATION_COMPONENT_APPLY\x10\b*{\n" +
	"\x10ComposeOwnerKind\x12\"\n" +
	"\x1eCOMPOSE_OWNER_KIND_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCOMPOSE_OWNER_KIND_ENVIRONMENT\x10\x01\x12\x1f\n" +
	"\x1bCOMPOSE_OWNER_KIND_PLATFORM\x10\x022j\n" +
	"\fAgentChannel\x12Z\n" +
	"\aConnect\x12\".groundplane.agent.v1.AgentMessage\x1a'.groundplane.agent.v1.ControllerMessage(\x010\x01B.Z,github.com/AlanD20/groundplane/proto/agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_agent_proto_goTypes = []any{
	(TaskState)(0),            // 0: groundplane.agent.v1.TaskState
	(TaskTerminal)(0),         // 1: groundplane.agent.v1.TaskTerminal
	(PlanOperation)(0),        // 2: groundplane.agent.v1.PlanOperation
	(ComposeOwnerKind)(0),     // 3: groundplane.agent.v1.ComposeOwnerKind
	(*Authenticate)(nil),      // 4: groundplane.agent.v1.Authenticate
	(*AgentConfig)(nil),       // 5: groundplane.agent.v1.AgentConfig
	(*AgentMessage)(nil),      // 6: groundplane.agent.v1.AgentMessage
	(*Ready)(nil),             // 7: groundplane.agent.v1.Ready
	(*TaskEvent)(nil),         // 8: groundplane.agent.v1.TaskEvent
	(*ObservedState)(nil),     // 9: groundplane.agent.v1.ObservedState
	(*ContainerState)(nil),    // 10: groundplane.agent.v1.ContainerState
	(*TaskAck)(nil),           // 11: groundplane.agent.v1.TaskAck
	(*ControllerMessage)(nil), // 12: groundplane.agent.v1.ControllerMessage
	(*TaskAssignment)(nil),    // 13: groundplane.agent.v1.TaskAssignment
	(*ExecutionPlan)(nil),     // 14: groundplane.agent.v1.ExecutionPlan
	(*ComposeArtifact)(nil),   // 15: groundplane.agent.v1.ComposeArtifact
	(*ComposeService)(nil),    // 16: groundplane.agent.v1.ComposeService
	(*ComposeNetwork)(nil),    // 17: groundplane.agent.v1.ComposeNetwork
	(*ComposeVolume)(nil),     // 18: groundplane.agent.v1.ComposeVolume
	(*LabelPair)(nil),         // 19: groundplane.agent.v1.LabelPair
	(*ExecutionStep)(nil),     // 20: groundplane.agent.v1.ExecutionStep
	(*ComposeApply)(nil),      // 21: groundplane.agent.v1.ComposeApply
	(*ComposeStop)(nil),       // 22: groundplane.agent.v1.ComposeStop
	(*ComposeRemove)(nil),     // 23: groundplane.agent.v1.ComposeRemove
	(*WaitHealthy)(nil),       // 24: groundplane.agent.v1.WaitHealthy
	(*TaskAbort)(nil),         // 25: groundplane.agent.v1.TaskAbort
	(*ConfigUpdate)(nil),      // 26: groundplane.agent.v1.ConfigUpdate
	(*Shutdown)(nil),          // 27: groundplane.agent.v1.Shutdown
	nil,                       // 28: groundplane.agent.v1.AgentConfig.LabelsEntry
	nil,                       // 29: groundplane.agent.v1.ContainerState.LabelsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	28, // 0: groundplane.agent.v1.AgentConfig.labels:type_name -> groundplane.agent.v1.AgentConfig.LabelsEntry
	4,  // 1: groundplane.agent.v1.AgentMessage.authenticate:type_name -> groundplane.agent.v1.Authenticate
	7,  // 2: groundplane.agent.v1.AgentMessage.ready:type_name -> groundplane.agent.v1.Ready
	8,  // 3: groundplane.agent.v1.AgentMessage.task_event:type_name -> groundplane.agent.v1.TaskEvent
	9,  // 4: groundplane.agent.v1.AgentMessage.observed_state:type_name -> groundplane.agent.v1.ObservedState
	11, // 5: groundplane.agent.v1.AgentMessage.task_ack:type_name -> groundplane.agent.v1.TaskAck
	0,  // 6: groundplane.agent.v1.TaskEvent.state:type_name -> groundplane.agent.v1.TaskState
	10, // 7: groundplane.agent.v1.ObservedState.containers:type_name -> groundplane.agent.v1.ContainerState
	29, // 8: groundplane.agent.v1.ContainerState.labels:type_name -> groundplane.agent.v1.ContainerState.LabelsEntry
	1,  // 9: groundplane.agent.v1.TaskAck.terminal:type_name -> groundplane.agent.v1.TaskTerminal
	13, // 10: groundplane.agent.v1.ControllerMessage.task_assignment:type_name -> groundplane.agent.v1.TaskAssignment
	25, // 11: groundplane.agent.v1.ControllerMessage.task_abort:type_name -> groundplane.agent.v1.TaskAbort
	26, // 12: groundplane.agent.v1.ControllerMessage.config_update:type_name -> groundplane.agent.v1.ConfigUpdate
	27, // 13: groundplane.agent.v1.ControllerMessage.shutdown:type_name -> groundplane.agent.v1.Shutdown
	14, // 14: groundplane.agent.v1.TaskAssignment.plan:type_name -> groundplane.agent.v1.ExecutionPlan
	2,  // 15: groundplane.agent.v1.ExecutionPlan.operation:type_name -> groundplane.agent.v1.PlanOperation
	15, // 16: groundplane.agent.v1.ExecutionPlan.artifacts:type_name -> groundplane.agent.v1.ComposeArtifact
	20, // 17: groundplane.agent.v1.ExecutionPlan.steps:type_name -> groundplane.agent.v1.ExecutionStep
	3,  // 18: groundplane.agent.v1.ComposeArtifact.owner_kind:type_name -> groundplane.agent.v1.ComposeOwnerKind
	16, // 19: groundplane.agent.v1.ComposeArtifact.services:type_name -> groundplane.agent.v1.ComposeService
	17, // 20: groundplane.agent.v1.ComposeArtifact.networks:type_name -> groundplane.agent.v1.ComposeNetwork
	18, // 21: groundplane.agent.v1.ComposeArtifact.volumes:type_name -> groundplane.agent.v1.ComposeVolume
	19, // 22: groundplane.agent.v1.ComposeService.expected_labels:type_name -> groundplane.agent.v1.LabelPair
	19, // 23: groundplane.agent.v1.ComposeNetwork.expected_labels:type_name -> groundplane.agent.v1.LabelPair
	19, // 24: groundplane.agent.v1.ComposeVolume.expected_labels:type_name -> groundplane.agent.v1.LabelPair
	21, // 25: groundplane.agent.v1.ExecutionStep.compose_apply:type_name -> groundplane.agent.v1.ComposeApply
	22, // 26: groundplane.agent.v1.ExecutionStep.compose_stop:type_name -> groundplane.agent.v1.ComposeStop
	23, // 27: groundplane.agent.v1.ExecutionStep.compose_remove:type_name -> groundplane.agent.v1.ComposeRemove
	24, // 28: groundplane.agent.v1.ExecutionStep.wait_healthy:type_name -> groundplane.agent.v1.WaitHealthy
	5,  // 29: groundplane.agent.v1.ConfigUpdate.agent_config:type_name -> groundplane.agent.v1.AgentConfig
	6,  // 30: groundplane.agent.v1.AgentChannel.Connect:input_type -> groundplane.agent.v1.AgentMessage
	12, // 31: groundplane.agent.v1.AgentChannel.Connect:output_type -> groundplane.agent.v1.ControllerMessage
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Authenticate)(nil),
		(*AgentMessage_Ready)(nil),
		(*AgentMessage_TaskEvent)(nil),
		(*AgentMessage_ObservedState)(nil),
		(*AgentMessage_TaskAck)(nil),
	}
	file_proto_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*ControllerMessage_TaskAssignment)(nil),
		(*ControllerMessage_TaskAbort)(nil),
		(*ControllerMessage_ConfigUpdate)(nil),
		(*ControllerMessage_Shutdown)(nil),
	}
	file_proto_agent_proto_msgTypes[16].OneofWrappers = []any{
		(*ExecutionStep_ComposeApply)(nil),
		(*ExecutionStep_ComposeStop)(nil),
		(*ExecutionStep_ComposeRemove)(nil),
		(*ExecutionStep_WaitHealthy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
