// The Controller <-> Agent machine contract. This .proto is the single
// source of truth — both sides compile against it, so a contract change
// is a build error, never a silent runtime mismatch. See mvp.md, "Agent
// channel (locked): gRPC + protobuf".
//
// One long-lived bidirectional stream per agent, INITIATED BY THE AGENT
// (dial-out, pull model): the Agent signals Ready and the Controller
// assigns work; nothing is ever pushed to an unconnected agent.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannel_Connect_FullMethodName = "/groundplane.agent.v1.AgentChannel/Connect"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentChannel is the one authenticated bidirectional stream. The Agent
// sends Authenticate as the first message and keeps the stream open for the
// life of the process, reconnecting with exponential backoff on drop.
type AgentChannelClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControllerMessage], error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControllerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControllerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ControllerMessage]

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility.
//
// AgentChannel is the one authenticated bidirectional stream. The Agent
// sends Authenticate as the first message and keeps the stream open for the
// life of the process, reconnecting with exponential backoff on drop.
type AgentChannelServer interface {
	Connect(grpc.BidiStreamingServer[AgentMessage, ControllerMessage]) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServer struct{}

func (UnimplementedAgentChannelServer) Connect(grpc.BidiStreamingServer[AgentMessage, ControllerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}
func (UnimplementedAgentChannelServer) testEmbeddedByValue()                      {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	// If the following call pancis, it indicates UnimplementedAgentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).Connect(&grpc.GenericServerStream[AgentMessage, ControllerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ControllerMessage]

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "groundplane.agent.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentChannel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
