"use client";

import { CopyButton } from "@/components/common/copy-button";
import { EmptyState } from "@/components/common/empty-state";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useStore } from "@/lib/store";
import type { Environment } from "@/lib/types";
import { Database } from "lucide-react";
import { useState } from "react";

export function FactsCard({ env }: { env: Environment }) {
  const store = useStore();
  const factGroups = env.attaches.flatMap((a) => {
    const g = store.getBackingProject(a.projectId);
    if (!g) return [];
    const sets = a.factSets.map((set) => ({
      label: set.grantAttachId
        ? `${g.name} · grant ${set.grantAttachId}`
        : `${g.name} · ${a.name}`,
      rows: set.facts.map((fact) => ({
        attachId: a.id,
        grantAttachId: set.grantAttachId,
        k: fact.key,
        secret: fact.secret,
      })),
    }));
    return [{ id: `facts-${a.id}`, title: `for ${a.service}`, sets }];
  });

  if (factGroups.length === 0)
    return (
      <EmptyState
        icon={<Database />}
        title="No Attach facts yet"
        description="Connect a Service to a backing service to publish its provisioning facts. Entries can reference those facts explicitly."
      />
    );

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Database className="size-4 text-muted-foreground" /> Shared infra ·
          facts
        </CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        <p className="text-xs text-muted-foreground">
          Attaching exposes{" "}
          <span className="font-medium text-foreground">
            facts, not injected vars
          </span>
          . Values are generated by the Controller and decrypted only through
          the explicit reveal action. Create env entries from these facts — the
          names are yours. A grant adds a fact set over the granted database.
        </p>
        {factGroups.map((grp) => (
          <div key={grp.id} className="flex flex-col gap-2">
            <span className="font-mono text-[11px] text-muted-foreground">
              {grp.title}
            </span>
            {grp.sets.map((set) => (
              <div
                key={set.label}
                className="flex flex-col gap-1 rounded-lg border border-border bg-surface px-3 py-2"
              >
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-medium">
                    {set.label}
                  </span>
                </div>
                <div className="flex flex-col gap-1 border-t border-border pt-1.5">
                  {set.rows.map((r) => (
                    <FactRow key={r.k} {...r} />
                  ))}
                </div>
              </div>
            ))}
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

export function FactRow({
  attachId,
  grantAttachId,
  k,
  secret,
}: {
  attachId: string;
  grantAttachId?: string;
  k: string;
  secret: boolean;
}) {
  const store = useStore();
  const [value, setValue] = useState<string>();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>();
  return (
    <div className="flex min-w-0 flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
      <span className="font-mono text-[11px] text-muted-foreground">{k}</span>
      <div className="flex min-w-0 max-w-full flex-1 items-start gap-2">
        <span className="min-w-0 max-h-40 flex-1 overflow-y-auto whitespace-pre-wrap font-mono text-[11px] text-foreground [overflow-wrap:anywhere]">
          {error ?? value ?? (secret ? "••••••••" : "not loaded")}
        </span>
        {value ? <CopyButton className="shrink-0" value={value} /> : null}
        <Button
          variant="ghost"
          className="shrink-0"
          size="sm"
          disabled={loading}
          onClick={() => {
            setLoading(true);
            setError(undefined);
            void store
              .revealAttachFact(attachId, k, grantAttachId)
              .then(setValue)
              .catch((cause: unknown) => {
                setError(
                  cause instanceof Error
                    ? cause.message
                    : "Unable to reveal fact",
                );
              })
              .finally(() => setLoading(false));
          }}
        >
          {loading ? "Loading…" : value ? "Refresh" : "Reveal"}
        </Button>
      </div>
    </div>
  );
}
