package etcd

const (
	// TaskResourceKindParam closes the durable Controller Task dispatch catalog.
	TaskResourceKindParam                = "resource_kind"
	TaskResourceAgent                    = "agent"
	TaskResourceEntry                    = "entry"
	TaskResourceRoute                    = "route"
	TaskResourceScript                   = "script"
	TaskResourceSecret                   = "secret"
	TaskResourceConnector                = "connector"
	TaskResourceBackingZone              = "backing_zone"
	TaskResourceService                  = "service"
	TaskResourceReleaseGroup             = "release_group"
	TaskResourceVolume                   = "volume"
	TaskResourceComponent                = "component"
	TaskResourceHierarchyDeletion        = "hierarchy_deletion"
	TaskHierarchyDeletionOperationParam  = "hierarchy_deletion_operation_id"
	TaskHierarchyDeletionTargetKindParam = "hierarchy_deletion_target_kind"
	TaskHierarchyDeletionParentParam     = "hierarchy_deletion_parent_operation_id"
	TaskHierarchyDeletionChildParam      = "hierarchy_deletion_child_operation_id"
	TaskHierarchyDeletionAttemptParam    = "hierarchy_deletion_attempt_id"
	TaskHierarchyDeletionGenerationParam = "hierarchy_deletion_attempt_generation"
	TaskHierarchyDeletionOrdinalParam    = "hierarchy_deletion_action_ordinal"
	TaskHierarchyDeletionActionKindParam = "hierarchy_deletion_action_kind"
	TaskHierarchyDeletionProcedureParam  = "hierarchy_deletion_typed_procedure"
	TaskHierarchyDeletionInputParam      = "hierarchy_deletion_input_digest"
	TaskComposeArtifactParam             = "compose_artifact_id"
	TaskEntryEnvironmentParam            = "entry_environment_id"
	TaskEntryTenantSlugParam             = "entry_tenant_slug"
	TaskEntryProjectSlugParam            = "entry_project_slug"
	TaskEntryEnvironmentNameParam        = "entry_environment_name"
	TaskEntryAuthorizedVolumeDirParam    = "entry_authorized_volume_dir"
	TaskRouteEnvironmentParam            = "route_environment_id"
	TaskServiceEnvironmentParam          = "service_environment_id"
	TaskZoneEnvironmentParam             = "zone_environment_id"
	TaskZoneImpactTokenParam             = "zone_impact_token"
	TaskZoneRemovalOperationParam        = "zone_removal_operation_id"
)
